name: 01 - Building Blocks
on:
  push:
  workflow_dispatch:

jobs:
  first job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
  second job:
    runs-on: ubuntu-latest
    steps:
      name: Say Goodbye
      run: echo "Goodbye"